-- Enable RLS on all PMT application tables
-- This hardens access at the database layer.
-- Service-role key calls from server routes continue to work.

ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Client" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Portfolio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Milestone" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Ticket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketChecklistItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TicketActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Document" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AutomationRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GithubBranch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GithubPullRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GithubRepo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedView" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PasswordReset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InviteToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BackupSnapshot" ENABLE ROW LEVEL SECURITY;

-- Optional strict mode: force RLS even for table owners.
-- Uncomment only if you have tested your server paths thoroughly.
-- ALTER TABLE "Team" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Client" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "TeamMembership" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Portfolio" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Project" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Milestone" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Ticket" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "TicketComment" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "TicketAttachment" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "TicketChecklistItem" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "TicketActivity" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Document" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "AutomationRule" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "GithubBranch" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "GithubPullRequest" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "GithubRepo" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "Notification" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "SavedView" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "OrganizationSettings" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "PasswordReset" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "InviteToken" FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "BackupSnapshot" FORCE ROW LEVEL SECURITY;
